### ISSUE TITLE
incorrect run deps

### ISSUE THREAD

**Issue by casperdcl** [conda-forge/scikit-build-feedstock#40]
https://github.com/conda-forge/scikit-build-feedstock/blob/42a722d4f7820c13fb32480afac14d9e8ca2a81e/recipe/meta.yaml#L29-L36 does not correspond to https://github.com/scikit-build/scikit-build/blob/a0cbcedea94514a92f3f9230825379fca2128fbd/requirements.txt, i.e. `cmake` and `ninja` should be removed.

**Comment by henryiii** [comment]
Conda often has more requirements than PyPI packages.

**Comment by casperdcl** [comment]
`cmake` and `ninja` are definitely not required in the conda `run` section. They are correctly in the `build` section further above: https://github.com/conda-forge/scikit-build-feedstock/blob/42a722d4f7820c13fb32480afac14d9e8ca2a81e/recipe/meta.yaml#L17-L22

Including them in the `run` section is unnecessary especially for people who already have `cmake` and e.g. `make`.

**Comment by henryiii** [comment]
You can't use scikit-build without cmake and some build system (ninja or make)? They are not required in the scikit-build PyPI package because a user might want to use the system packages, but in conda-forge, we can provide all packages - conda is not intended to mix with the system tools.

**Comment by casperdcl** [comment]
> conda is not intended to mix with the system tools

in that case the `run` section is missing

```
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

as well as all compilers supported by cmake (CUDA etc.)

**Comment by henryiii** [comment]
No, you don't know what compiler someone will need. There's no need to install a C compiler if you only are using C++. Cross compiling is also sometimes needed.

However, you always need CMake. You can't do anything with scikit-build without CMake.

**Comment by henryiii** [comment]
(You could argue someone could chose make vs. ninja, but ninja is the best supported platform and is always usable, so I don't think there's harm in requiring it here)
