### ISSUE TITLE
System cmake3 binary used even though conda-forge cmake is intalled

### ISSUE THREAD

**Issue by ngoldbaum** [conda-forge/scikit-build-feedstock#78]
I'm helping someone debug an issue building some software in a conda environment. The package they're building uses scikit-build and they happen to have a `/usr/bin/cmake3` executable in their PATH. See [here](https://github.com/Point72/csp/issues/73).

Because of [these lines](https://github.com/scikit-build/scikit-build/blob/bbd0bd0436d85951386292c3413027d4364319d7/skbuild/constants.py#L26-L27) in scikit-build, the `/usr/bin/cmake3` executable is always found first before the `cmake` executable on the user's `PATH` that comes from the conda-forge cmake package. The `cmake` package doesn't install a `cmake3` binary.

I'm filing this here because I think the feedstock could make a patch to `scikit-build` to work around this by e.g. switching the order of `cmake` and `cmake3` in the check for the cmake executable. The fix could also go upstream too if permanently changing that order makes sense. Another fix would be to install a `cmake3` executable along with `cmake` in the cmake feedstock.

**Comment by henryiii** [comment]
I think what might make the most sense is to try to find cmake first, and only fall back to cmake3 if the version is insufficient. Old RHEL based systems have old “cmake” but newer cmake3, usually.

**Comment by ngoldbaum** [comment]
Good point, I'll open an issue about this against scikit-build. Thanks for responding so quickly!
